[2025-09-01 19:25:25] [INFO    ] discord.client: logging in using static token
[2025-09-01 19:25:25] [DEBUG   ] discord.http: GET https://discord.com/api/v10/users/@me with None has returned 200
[2025-09-01 19:25:25] [DEBUG   ] discord.http: GET /users/@me has found its initial rate limit bucket hash (78bb8553d9352a5a2f89f9def401287a).
[2025-09-01 19:25:25] [DEBUG   ] discord.http: GET https://discord.com/api/v10/users/@me has received {'id': '1394877805241696328', 'username': 'Yoimiya', 'avatar': '95f18a9a36a6cb0d5c4af5ac3d3637cf', 'discriminator': '4246', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': 'e1657a441fbc2fb68fb96f664c70f807', 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'collectibles': None, 'display_name_styles': None, 'banner_color': None, 'clan': None, 'primary_guild': None, 'mfa_enabled': False, 'locale': 'en-US', 'premium_type': 0, 'email': None, 'verified': True, 'bio': ''}
[2025-09-01 19:25:26] [DEBUG   ] discord.http: GET https://discord.com/api/v10/oauth2/applications/@me with None has returned 200
[2025-09-01 19:25:26] [DEBUG   ] discord.http: GET /oauth2/applications/@me has found its initial rate limit bucket hash (d28a133af187e91d71d96a223467ce49).
[2025-09-01 19:25:26] [DEBUG   ] discord.http: GET https://discord.com/api/v10/oauth2/applications/@me has received {'id': '1394877805241696328', 'name': 'Yoimiya', 'icon': '95f18a9a36a6cb0d5c4af5ac3d3637cf', 'description': 'A Ai bot created by Fano.', 'type': None, 'bot': {'id': '1394877805241696328', 'username': 'Yoimiya', 'avatar': '95f18a9a36a6cb0d5c4af5ac3d3637cf', 'discriminator': '4246', 'public_flags': 0, 'flags': 0, 'bot': True, 'banner': 'e1657a441fbc2fb68fb96f664c70f807', 'accent_color': None, 'global_name': None, 'avatar_decoration_data': None, 'collectibles': None, 'display_name_styles': None, 'banner_color': None, 'clan': None, 'primary_guild': None}, 'summary': '', 'is_monetized': False, 'is_verified': False, 'is_discoverable': False, 'bot_public': True, 'bot_require_code_grant': False, 'install_params': {'scopes': ['applications.commands'], 'permissions': '0'}, 'integration_types_config': {'0': {'oauth2_install_params': {'scopes': ['applications.commands'], 'permissions': '0'}}, '1': {'oauth2_install_params': {'scopes': ['applications.commands'], 'permissions': '0'}}}, 'verify_key': 'ac6bb4922d10098ce4fab96b3a727e8217bae7359a9253666ce263207a03890d', 'flags': 557056, 'hook': True, 'storefront_available': False, 'redirect_uris': [], 'interactions_endpoint_url': None, 'role_connections_verification_url': None, 'owner': {'id': '978304668520312842', 'username': 'fanoalone', 'avatar': 'd81de0fb8a9251467adf3d244837e2c5', 'discriminator': '0', 'public_flags': 0, 'flags': 0, 'banner': None, 'accent_color': 11399151, 'global_name': 'FanoAlone', 'avatar_decoration_data': None, 'collectibles': None, 'display_name_styles': None, 'banner_color': '#adefef', 'clan': None, 'primary_guild': None}, 'approximate_guild_count': 3, 'approximate_user_install_count': 1, 'approximate_user_authorization_count': 1, 'interactions_event_types': [], 'interactions_version': 1, 'explicit_content_filter': 0, 'rpc_application_state': 0, 'store_application_state': 1, 'verification_state': 1, 'integration_public': True, 'integration_require_code_grant': False, 'discoverability_state': 1, 'discovery_eligibility_flags': 228, 'monetization_state': 1, 'verification_eligibility_flags': 91036, 'monetization_eligibility_flags': 181988, 'team': None, 'internal_guild_restriction': 2, 'approved_consoles': [], 'pricing_localization_strategy': 'localized_price_sets'}
[2025-09-01 19:25:27] [DEBUG   ] discord.gateway: Created websocket connected to wss://gateway.discord.gg/
[2025-09-01 19:25:27] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-arm-us-east1-c-v992",{"micros":0.0}]']}}
[2025-09-01 19:25:27] [DEBUG   ] discord.gateway: Shard ID None has sent the IDENTIFY payload.
[2025-09-01 19:25:27] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:25:28] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'READY', 's': 1, 'op': 0, 'd': {'v': 10, 'user_settings': {}, 'user': {'verified': True, 'username': 'Yoimiya', 'primary_guild': None, 'mfa_enabled': False, 'id': '1394877805241696328', 'global_name': None, 'flags': 0, 'email': None, 'discriminator': '4246', 'clan': None, 'bot': True, 'avatar': '95f18a9a36a6cb0d5c4af5ac3d3637cf'}, 'session_type': 'normal', 'session_id': 'd819885b51306e5d945dd25ed922f962', 'resume_gateway_url': 'wss://gateway-us-east1-c.discord.gg', 'relationships': [], 'private_channels': [], 'presences': [], 'guilds': [{'unavailable': True, 'id': '979000931146420244'}], 'guild_join_requests': [], 'geo_ordered_rtc_regions': ['india', 'hongkong', 'dubai', 'singapore', 'saudi-arabia'], 'game_relationships': [], 'auth': {}, 'application': {'id': '1394877805241696328', 'flags': 557056}, '_trace': ['["gateway-prd-arm-us-east1-c-v992",{"micros":88888,"calls":["id_created",{"micros":417,"calls":[]},"session_lookup_time",{"micros":346,"calls":[]},"session_lookup_finished",{"micros":10,"calls":[]},"discord-sessions-prd-2-59",{"micros":87395,"calls":["start_session",{"micros":72457,"calls":["discord-api-rpc-6bbfb49fc7-d4ztk",{"micros":44853,"calls":["get_user",{"micros":5432},"get_guilds",{"micros":2948},"send_scheduled_deletion_message",{"micros":10},"guild_join_requests",{"micros":2640},"authorized_ip_coro",{"micros":11},"pending_payments",{"micros":18606},"apex_experiments",{"micros":2507},"user_activities",{"micros":5},"played_application_ids",{"micros":9}]}]},"starting_guild_connect",{"micros":81,"calls":[]},"presence_started",{"micros":9137,"calls":[]},"guilds_started",{"micros":62,"calls":[]},"lobbies_started",{"micros":1,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":5639,"calls":[]},"connect_finished",{"micros":5643,"calls":[]},"build_ready",{"micros":12,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}]']}}
[2025-09-01 19:25:28] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:25:28] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d819885b51306e5d945dd25ed922f962).
[2025-09-01 19:25:28] [DEBUG   ] discord.client: Dispatching event connect
[2025-09-01 19:25:28] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'GUILD_CREATE', 's': 2, 'op': 0, 'd': {'splash': None, 'max_video_channel_users': 25, 'nsfw_level': 0, 'unavailable': False, 'incidents_data': None, 'home_header': None, 'owner_id': '978304668520312842', 'profile': None, 'inventory_settings': None, 'features': [], 'region': 'deprecated', 'voice_states': [], 'channels': [{'version': 1665245004607, 'type': 4, 'position': 0, 'permission_overwrites': [], 'name': 'General', 'id': '979000931146420245', 'flags': 0}, {'version': 0, 'type': 4, 'position': 0, 'permission_overwrites': [], 'name': 'Voice Channels', 'id': '979000931146420246', 'flags': 0}, {'version': 1665217741192, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'general', 'last_message_id': '1412018040736059423', 'id': '979000931146420247', 'flags': 0}, {'version': 0, 'user_limit': 0, 'type': 2, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [], 'parent_id': '979000931146420246', 'name': 'General', 'last_message_id': None, 'id': '979000931146420248', 'flags': 0, 'bitrate': 64000}, {'version': 1743174319325, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 5, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'parent_id': '979000931146420245', 'name': 'test', 'last_message_id': '1333562625304297533', 'id': '990156958482984990', 'flags': 0}, {'version': 0, 'user_limit': 0, 'type': 2, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [], 'parent_id': '979000931146420246', 'name': 'Lofi-Music Channel', 'last_message_id': '1029594896371286037', 'id': '1017054575083135026', 'flags': 0, 'bitrate': 64000}, {'version': 1743523845194, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 4, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'coding-and-cv', 'last_message_id': '1229068091967799376', 'id': '1023595181020282950', 'flags': 0}, {'version': 1665244917545, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 3, 'permission_overwrites': [], 'parent_id': '1028336409498615849', 'name': 'aternos-mcpe', 'last_message_id': '1024660501206143036', 'id': '1024656415282954353', 'flags': 0}, {'version': 1743523863357, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 6, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'website-crash', 'last_message_id': '1027499229263958066', 'id': '1025744851251241000', 'flags': 0}, {'version': 1743523891127, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 7, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'cmdnd', 'last_message_id': '1217375291161313331', 'id': '1026143126831767622', 'flags': 0}, {'version': 1743523911399, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 8, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'ethical-hcking', 'last_message_id': '1038481926270492713', 'id': '1026932353723011182', 'flags': 0}, {'version': 1743523991698, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 9, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'general-trobule-shooting', 'last_message_id': '1291726645174075424', 'id': '1028220885854867508', 'flags': 0}, {'version': 1665244968706, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 10, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028336409498615849', 'name': 'cr', 'last_message_id': '1408438607412334687', 'id': '1028226725961805855', 'flags': 0}, {'version': 1743174319384, 'type': 4, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1049600', 'allow': '0'}], 'name': 'Coding & Techical', 'id': '1028335612488597544', 'flags': 0}, {'version': 1665244905595, 'type': 4, 'position': 2, 'permission_overwrites': [], 'name': 'Game news and event', 'id': '1028336409498615849', 'flags': 0}, {'version': 1665300153588, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 11, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'youtube', 'last_message_id': '1207329449612415026', 'id': '1028568136380846090', 'flags': 0}, {'version': 1665302846910, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 12, 'permission_overwrites': [], 'parent_id': '1028336409498615849', 'name': 'cn', 'last_message_id': '1333564013635834001', 'id': '1028579432987906108', 'flags': 0}, {'version': 1665542368815, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 13, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'name': 'nerdy-questions', 'last_message_id': '1040606428777435137', 'id': '1029584060667932722', 'flags': 0}, {'version': 1665747912555, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 14, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'repair', 'last_message_id': '1355209333251506328', 'id': '1030446173607165962', 'flags': 0}, {'version': 1666014003523, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 15, 'permission_overwrites': [], 'parent_id': '1028336409498615849', 'name': 'goals', 'last_message_id': '1355205985358319748', 'id': '1031562240006037504', 'flags': 0}, {'version': 1743524014718, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 16, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'useful-wbsite', 'last_message_id': '1207317225380380743', 'id': '1035469749242568774', 'flags': 0}, {'version': 1667051327825, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 17, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'projects', 'last_message_id': '1051460356725289060', 'id': '1035913093475217479', 'flags': 0}, {'version': 1667553124408, 'type': 0, 'topic': '<:hydra_play:971015680600199178> Pause/Resume the song.\n<:hydra_stop:971015680696672356> Stop and empty the queue.\n<:hydra_skip:971015680654729216> Skip the song.\n<:hydra_loop_off:971015680629559296> Switch between the loop modes.\n<:hydra_shuffle:971015680633741312> Shuffle the queue.\n<:hydra_button_green:974274003659292682> Add the current song to your private playlist.\n<:hydra_button_red:974274003663482880> Remove the current song from your private playlist.', 'rate_limit_per_user': 0, 'position': 18, 'permission_overwrites': [], 'name': 'hydra-song-requests', 'last_message_id': '1039157009464971354', 'id': '1038017780458475560', 'flags': 0}, {'version': 1674878131820, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 19, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '805307408', 'allow': '0'}], 'parent_id': '979000931146420245', 'name': 'passwords', 'last_message_id': '1068743246223773766', 'id': '1068740321724338318', 'flags': 0}, {'version': 1675778363272, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 20, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'code-share', 'last_message_id': '1072516954176368650', 'id': '1072516933171294218', 'flags': 0}, {'version': 1743524031708, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 21, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'robot-making', 'last_message_id': '1208283944789737493', 'id': '1207328608717115392', 'flags': 0}, {'version': 1711252141839, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 22, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'name': 'job', 'last_message_id': '1221304816748462201', 'id': '1221304744505507901', 'flags': 0}, {'version': 1743173041124, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 23, 'permission_overwrites': [], 'name': 'bot', 'last_message_id': '1355212618184265830', 'id': '1355190602039296234', 'flags': 0, 'default_auto_archive_duration': 10080}, {'version': 1743523763295, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 24, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'skill-dev', 'last_message_id': '1358052497448505355', 'id': '1356661735477743727', 'flags': 0}, {'version': 1756721768124, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 25, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'playground', 'last_message_id': '1412019521686077564', 'id': '1412018179873701899', 'flags': 0}], 'safety_alerts_channel_id': None, 'id': '979000931146420244', 'banner': None, 'default_message_notifications': 0, 'roles': [{'version': 0, 'unicode_emoji': None, 'tags': {}, 'position': 0, 'permissions': '2248471318351425', 'name': '@everyone', 'mentionable': False, 'managed': False, 'id': '979000931146420244', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 0}, 'color': 0}, {'version': 1707532506403, 'unicode_emoji': None, 'tags': {}, 'position': 4, 'permissions': '28587301797887', 'name': 'Admin', 'mentionable': False, 'managed': False, 'id': '989846861978431508', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 16711680}, 'color': 16711680}, {'version': 1707532506900, 'unicode_emoji': None, 'tags': {}, 'position': 3, 'permissions': '1069551176257', 'name': 'new role', 'mentionable': False, 'managed': False, 'id': '990276009444134962', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 0}, 'color': 0}, {'version': 1756721734849, 'unicode_emoji': None, 'tags': {'bot_id': '1394877805241696328'}, 'position': 1, 'permissions': '8', 'name': 'Yoimiya', 'mentionable': False, 'managed': True, 'id': '1412018040312168513', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 0}, 'color': 0}], 'premium_subscription_count': 0, 'latest_onboarding_question_id': None, 'system_channel_flags': 0, 'name': "Fano's server", 'hub_type': None, 'mfa_level': 0, 'members': [{'user': {'username': 'Yoimiya', 'public_flags': 0, 'primary_guild': None, 'id': '1394877805241696328', 'global_name': None, 'display_name_styles': None, 'display_name': None, 'discriminator': '4246', 'collectibles': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '95f18a9a36a6cb0d5c4af5ac3d3637cf'}, 'roles': ['1412018040312168513'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2025-09-01T10:15:34.859000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}], 'preferred_locale': 'en-US', 'nsfw': False, 'threads': [], 'afk_timeout': 300, 'max_stage_video_channel_users': 50, 'description': None, 'soundboard_sounds': [], 'vanity_url_code': None, 'explicit_content_filter': 0, 'afk_channel_id': None, 'premium_progress_bar_enabled': True, 'large': False, 'activity_instances': [], 'presences': [], 'embedded_activities': [], 'stage_instances': [], 'rules_channel_id': None, 'icon': '42e9fc87fbb80c6f6442726d9ba8bcb2', 'discovery_splash': None, 'lazy': True, 'premium_tier': 0, 'application_id': None, 'system_channel_id': '979000931146420247', 'stickers': [], 'premium_features': None, 'version': 1743172916024, 'max_members': 25000000, 'public_updates_channel_id': None, 'member_count': 2, 'guild_scheduled_events': [], 'moderator_reporting': None, 'verification_level': 0, 'application_command_counts': {}, 'owner_configured_content_level': 0, 'joined_at': '2025-09-01T10:15:34.859000+00:00', 'emojis': []}}
[2025-09-01 19:25:28] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:25:28] [DEBUG   ] discord.client: Dispatching event guild_available
[2025-09-01 19:25:30] [DEBUG   ] discord.client: Dispatching event ready
[2025-09-01 19:25:38] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 3, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2025-09-01T13:40:38.227000+00:00', 'pinned': False, 'nonce': '1412069645329891328', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['989846861978431508'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2022-05-25T12:40:10.956000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1412069644470194227', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!genImg HD quality Futuristic, high-tech city at dusk. Neon lights reflecting off wet pavement. Rain-soaked streets, puddles reflecting city lights. Infrared glow of skyscrapers piercing through the misty atmosphere. A lone figure in the distance, shrouded in shadows in A4 paper aspect rationn', 'components': [], 'channel_type': 0, 'channel_id': '1412018179873701899', 'author': {'username': 'fanoalone', 'public_flags': 0, 'primary_guild': None, 'id': '978304668520312842', 'global_name': 'FanoAlone', 'display_name_styles': None, 'discriminator': '0', 'collectibles': None, 'clan': None, 'avatar_decoration_data': None, 'avatar': 'd81de0fb8a9251467adf3d244837e2c5'}, 'attachments': [], 'guild_id': '979000931146420244'}}
[2025-09-01 19:25:38] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:25:38] [DEBUG   ] discord.client: Dispatching event message
[2025-09-01 19:25:38] [DEBUG   ] discord.client: Dispatching event command
[2025-09-01 19:25:40] [DEBUG   ] discord.client: Dispatching event command_error
[2025-09-01 19:25:40] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command genImg
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\USER\Desktop\projects\discordBot\ForTest\main.py", line 82, in genImg
    GenerateImage(content)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\USER\Desktop\projects\discordBot\ForTest\protocol\protocolParser.py", line 30, in GenerateImage
    response = client.models.generate_content(
    # model="gemini-2.0-flash-exp-image-generation",
    ...<4 lines>...
        )
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\models.py", line 5164, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=config
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\models.py", line 4239, in _generate_content
    response_dict = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\_api_client.py", line 553, in request
    response = self._request(http_request, stream=False)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\_api_client.py", line 467, in _request
    return self._request_unauthorized(http_request, stream)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\_api_client.py", line 490, in _request_unauthorized
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\errors.py", line 115, in raise_for_response
    raise ClientError(status_code, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash-preview-image', 'location': 'global'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '19s'}]}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash-preview-image', 'location': 'global'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '19s'}]}}
[2025-09-01 19:25:40] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'TYPING_START', 's': 4, 'op': 0, 'd': {'user_id': '978304668520312842', 'timestamp': 1756734039, 'member': {'user': {'username': 'fanoalone', 'public_flags': 0, 'primary_guild': None, 'id': '978304668520312842', 'global_name': 'FanoAlone', 'display_name_styles': None, 'display_name': 'FanoAlone', 'discriminator': '0', 'collectibles': None, 'bot': False, 'avatar_decoration_data': None, 'avatar': 'd81de0fb8a9251467adf3d244837e2c5'}, 'roles': ['989846861978431508'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2022-05-25T12:40:10.956000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'channel_id': '1412018179873701899', 'guild_id': '979000931146420244'}}
[2025-09-01 19:25:40] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:25:40] [DEBUG   ] discord.client: Dispatching event typing
[2025-09-01 19:25:40] [DEBUG   ] discord.client: Dispatching event raw_typing
[2025-09-01 19:26:08] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 4.
[2025-09-01 19:26:09] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:26:14] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 5, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2025-09-01T13:41:13.779000+00:00', 'pinned': False, 'nonce': '1412069793611120640', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': ['989846861978431508'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2022-05-25T12:40:10.956000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}, 'id': '1412069793586217040', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '!genImg HD quality Futuristic, high-tech city at dusk. Neon lights reflecting off wet pavement. Rain-soaked streets, puddles reflecting city lights. Infrared glow of skyscrapers piercing through the misty atmosphere. A lone figure in the distance, shrouded in shadows in A4 paper aspect rationn', 'components': [], 'channel_type': 0, 'channel_id': '1412018179873701899', 'author': {'username': 'fanoalone', 'public_flags': 0, 'primary_guild': None, 'id': '978304668520312842', 'global_name': 'FanoAlone', 'display_name_styles': None, 'discriminator': '0', 'collectibles': None, 'clan': None, 'avatar_decoration_data': None, 'avatar': 'd81de0fb8a9251467adf3d244837e2c5'}, 'attachments': [], 'guild_id': '979000931146420244'}}
[2025-09-01 19:26:14] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:26:14] [DEBUG   ] discord.client: Dispatching event message
[2025-09-01 19:26:14] [DEBUG   ] discord.client: Dispatching event command
[2025-09-01 19:26:16] [DEBUG   ] discord.client: Dispatching event command_error
[2025-09-01 19:26:16] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command genImg
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\USER\Desktop\projects\discordBot\ForTest\main.py", line 82, in genImg
    GenerateImage(content)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "c:\Users\USER\Desktop\projects\discordBot\ForTest\protocol\protocolParser.py", line 30, in GenerateImage
    response = client.models.generate_content(
    # model="gemini-2.0-flash-exp-image-generation",
    ...<4 lines>...
        )
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\models.py", line 5164, in generate_content
    response = self._generate_content(
        model=model, contents=contents, config=config
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\models.py", line 4239, in _generate_content
    response_dict = self._api_client.request(
        'post', path, request_dict, http_options
    )
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\_api_client.py", line 553, in request
    response = self._request(http_request, stream=False)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\_api_client.py", line 467, in _request
    return self._request_unauthorized(http_request, stream)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\_api_client.py", line 490, in _request_unauthorized
    errors.APIError.raise_for_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\google\genai\errors.py", line 115, in raise_for_response
    raise ClientError(status_code, response)
google.genai.errors.ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '44s'}]}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientError: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_input_token_count', 'quotaId': 'GenerateContentInputTokensPerModelPerMinute-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}, {'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash-preview-image'}}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '44s'}]}}
[2025-09-01 19:26:50] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:26:51] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:27:31] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:27:32] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:28:12] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:28:13] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:28:53] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:28:54] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:29:35] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:29:35] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:30:16] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:30:18] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:30:57] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:30:58] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:31:38] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 5.
[2025-09-01 19:31:39] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:37:43] [WARNING ] discord.gateway: Shard ID None has stopped responding to the gateway. Closing and restarting.
[2025-09-01 19:37:43] [DEBUG   ] discord.gateway: Timed out receiving packet. Attempting a reconnect.
[2025-09-01 19:37:43] [DEBUG   ] discord.client: Got a request to RESUME the websocket.
[2025-09-01 19:37:43] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:37:43] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:37:43] [ERROR   ] discord.client: Attempting a reconnect in 0.84s
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1532, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1148, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1179, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 1067, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1538, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [getaddrinfo failed]
[2025-09-01 19:37:44] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:37:44] [ERROR   ] discord.client: Attempting a reconnect in 2.03s
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1532, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1148, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1179, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 1067, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1538, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [getaddrinfo failed]
[2025-09-01 19:37:46] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:37:46] [ERROR   ] discord.client: Attempting a reconnect in 3.92s
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1532, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1148, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1179, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 1067, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1538, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [getaddrinfo failed]
[2025-09-01 19:37:50] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:37:50] [ERROR   ] discord.client: Attempting a reconnect in 11.80s
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1532, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1148, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1179, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 1067, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1538, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [getaddrinfo failed]
[2025-09-01 19:38:13] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:38:13] [ERROR   ] discord.client: Attempting a reconnect in 22.81s
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1532, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1148, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1179, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\resolver.py", line 40, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 939, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 977, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 1067, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 770, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 725, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 642, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1538, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [getaddrinfo failed]
[2025-09-01 19:38:36] [DEBUG   ] discord.gateway: Created websocket connected to wss://gateway-us-east1-c.discord.gg
[2025-09-01 19:38:36] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-arm-us-east1-c-7g4k",{"micros":0.0}]']}}
[2025-09-01 19:38:36] [DEBUG   ] discord.gateway: Shard ID None has sent the RESUME payload.
[2025-09-01 19:38:37] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:38:37] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 9, 'd': False}
[2025-09-01 19:38:37] [INFO    ] discord.gateway: Shard ID None session has been invalidated.
[2025-09-01 19:38:37] [DEBUG   ] discord.client: Got a request to IDENTIFY the websocket.
[2025-09-01 19:38:37] [DEBUG   ] discord.client: Dispatching event disconnect
[2025-09-01 19:38:38] [DEBUG   ] discord.gateway: Created websocket connected to wss://gateway-us-east1-c.discord.gg
[2025-09-01 19:38:38] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-arm-us-east1-c-jgkz",{"micros":0.0}]']}}
[2025-09-01 19:38:43] [DEBUG   ] discord.gateway: Shard ID None has sent the IDENTIFY payload.
[2025-09-01 19:38:43] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
[2025-09-01 19:38:44] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'READY', 's': 1, 'op': 0, 'd': {'v': 10, 'user_settings': {}, 'user': {'verified': True, 'username': 'Yoimiya', 'primary_guild': None, 'mfa_enabled': False, 'id': '1394877805241696328', 'global_name': None, 'flags': 0, 'email': None, 'discriminator': '4246', 'clan': None, 'bot': True, 'avatar': '95f18a9a36a6cb0d5c4af5ac3d3637cf'}, 'session_type': 'normal', 'session_id': '6f905a786898bd6ec23302e638daa59d', 'resume_gateway_url': 'wss://gateway-us-east1-c.discord.gg', 'relationships': [], 'private_channels': [], 'presences': [], 'guilds': [{'unavailable': True, 'id': '979000931146420244'}], 'guild_join_requests': [], 'geo_ordered_rtc_regions': ['india', 'hongkong', 'dubai', 'singapore', 'saudi-arabia'], 'game_relationships': [], 'auth': {}, 'application': {'id': '1394877805241696328', 'flags': 557056}, '_trace': ['["gateway-prd-arm-us-east1-c-jgkz",{"micros":70110,"calls":["id_created",{"micros":431,"calls":[]},"session_lookup_time",{"micros":216,"calls":[]},"session_lookup_finished",{"micros":9,"calls":[]},"discord-sessions-prd-2-116",{"micros":67964,"calls":["start_session",{"micros":65588,"calls":["discord-api-rpc-6bbfb49fc7-kchqt",{"micros":45740,"calls":["get_user",{"micros":8763},"get_guilds",{"micros":4886},"send_scheduled_deletion_message",{"micros":11},"guild_join_requests",{"micros":438},"authorized_ip_coro",{"micros":9},"pending_payments",{"micros":11502},"apex_experiments",{"micros":2212},"user_activities",{"micros":3},"played_application_ids",{"micros":2}]}]},"starting_guild_connect",{"micros":64,"calls":[]},"presence_started",{"micros":579,"calls":[]},"guilds_started",{"micros":54,"calls":[]},"lobbies_started",{"micros":1,"calls":[]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":1663,"calls":[]},"connect_finished",{"micros":1668,"calls":[]},"build_ready",{"micros":9,"calls":[]},"clean_ready",{"micros":0,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":0,"calls":[]}]}]}]']}}
[2025-09-01 19:38:44] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:38:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6f905a786898bd6ec23302e638daa59d).
[2025-09-01 19:38:44] [DEBUG   ] discord.client: Dispatching event connect
[2025-09-01 19:38:44] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'GUILD_CREATE', 's': 2, 'op': 0, 'd': {'premium_progress_bar_enabled': True, 'stickers': [], 'preferred_locale': 'en-US', 'voice_states': [], 'moderator_reporting': None, 'embedded_activities': [], 'vanity_url_code': None, 'profile': None, 'max_video_channel_users': 25, 'banner': None, 'safety_alerts_channel_id': None, 'rules_channel_id': None, 'max_members': 25000000, 'member_count': 2, 'afk_channel_id': None, 'lazy': True, 'inventory_settings': None, 'owner_id': '978304668520312842', 'icon': '42e9fc87fbb80c6f6442726d9ba8bcb2', 'nsfw': False, 'id': '979000931146420244', 'system_channel_flags': 0, 'premium_features': None, 'name': "Fano's server", 'unavailable': False, 'application_command_counts': {}, 'threads': [], 'large': False, 'afk_timeout': 300, 'description': None, 'guild_scheduled_events': [], 'system_channel_id': '979000931146420247', 'nsfw_level': 0, 'explicit_content_filter': 0, 'splash': None, 'activity_instances': [], 'incidents_data': None, 'discovery_splash': None, 'verification_level': 0, 'max_stage_video_channel_users': 50, 'stage_instances': [], 'mfa_level': 0, 'members': [{'user': {'username': 'Yoimiya', 'public_flags': 0, 'primary_guild': None, 'id': '1394877805241696328', 'global_name': None, 'display_name_styles': None, 'display_name': None, 'discriminator': '4246', 'collectibles': None, 'bot': True, 'avatar_decoration_data': None, 'avatar': '95f18a9a36a6cb0d5c4af5ac3d3637cf'}, 'roles': ['1412018040312168513'], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2025-09-01T10:15:34.859000+00:00', 'flags': 0, 'deaf': False, 'communication_disabled_until': None, 'banner': None, 'avatar': None}], 'hub_type': None, 'joined_at': '2025-09-01T10:15:34.859000+00:00', 'premium_subscription_count': 0, 'owner_configured_content_level': 0, 'application_id': None, 'premium_tier': 0, 'public_updates_channel_id': None, 'presences': [], 'soundboard_sounds': [], 'roles': [{'version': 0, 'unicode_emoji': None, 'tags': {}, 'position': 0, 'permissions': '2248471318351425', 'name': '@everyone', 'mentionable': False, 'managed': False, 'id': '979000931146420244', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 0}, 'color': 0}, {'version': 1707532506403, 'unicode_emoji': None, 'tags': {}, 'position': 4, 'permissions': '28587301797887', 'name': 'Admin', 'mentionable': False, 'managed': False, 'id': '989846861978431508', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 16711680}, 'color': 16711680}, {'version': 1707532506900, 'unicode_emoji': None, 'tags': {}, 'position': 3, 'permissions': '1069551176257', 'name': 'new role', 'mentionable': False, 'managed': False, 'id': '990276009444134962', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 0}, 'color': 0}, {'version': 1756721734849, 'unicode_emoji': None, 'tags': {'bot_id': '1394877805241696328'}, 'position': 1, 'permissions': '8', 'name': 'Yoimiya', 'mentionable': False, 'managed': True, 'id': '1412018040312168513', 'icon': None, 'hoist': False, 'flags': 0, 'colors': {'tertiary_color': None, 'secondary_color': None, 'primary_color': 0}, 'color': 0}], 'region': 'deprecated', 'version': 1743172916024, 'latest_onboarding_question_id': None, 'emojis': [], 'home_header': None, 'default_message_notifications': 0, 'features': [], 'channels': [{'version': 1665245004607, 'type': 4, 'position': 0, 'permission_overwrites': [], 'name': 'General', 'id': '979000931146420245', 'flags': 0}, {'version': 0, 'type': 4, 'position': 0, 'permission_overwrites': [], 'name': 'Voice Channels', 'id': '979000931146420246', 'flags': 0}, {'version': 1665217741192, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'general', 'last_message_id': '1412018040736059423', 'id': '979000931146420247', 'flags': 0}, {'version': 0, 'user_limit': 0, 'type': 2, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 0, 'permission_overwrites': [], 'parent_id': '979000931146420246', 'name': 'General', 'last_message_id': None, 'id': '979000931146420248', 'flags': 0, 'bitrate': 64000}, {'version': 1743174319325, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 5, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'parent_id': '979000931146420245', 'name': 'test', 'last_message_id': '1333562625304297533', 'id': '990156958482984990', 'flags': 0}, {'version': 0, 'user_limit': 0, 'type': 2, 'rtc_region': None, 'rate_limit_per_user': 0, 'position': 1, 'permission_overwrites': [], 'parent_id': '979000931146420246', 'name': 'Lofi-Music Channel', 'last_message_id': '1029594896371286037', 'id': '1017054575083135026', 'flags': 0, 'bitrate': 64000}, {'version': 1743523845194, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 4, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'coding-and-cv', 'last_message_id': '1229068091967799376', 'id': '1023595181020282950', 'flags': 0}, {'version': 1665244917545, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 3, 'permission_overwrites': [], 'parent_id': '1028336409498615849', 'name': 'aternos-mcpe', 'last_message_id': '1024660501206143036', 'id': '1024656415282954353', 'flags': 0}, {'version': 1743523863357, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 6, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'website-crash', 'last_message_id': '1027499229263958066', 'id': '1025744851251241000', 'flags': 0}, {'version': 1743523891127, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 7, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'cmdnd', 'last_message_id': '1217375291161313331', 'id': '1026143126831767622', 'flags': 0}, {'version': 1743523911399, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 8, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'ethical-hcking', 'last_message_id': '1038481926270492713', 'id': '1026932353723011182', 'flags': 0}, {'version': 1743523991698, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 9, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'general-trobule-shooting', 'last_message_id': '1291726645174075424', 'id': '1028220885854867508', 'flags': 0}, {'version': 1665244968706, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 10, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028336409498615849', 'name': 'cr', 'last_message_id': '1408438607412334687', 'id': '1028226725961805855', 'flags': 0}, {'version': 1743174319384, 'type': 4, 'position': 1, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1049600', 'allow': '0'}], 'name': 'Coding & Techical', 'id': '1028335612488597544', 'flags': 0}, {'version': 1665244905595, 'type': 4, 'position': 2, 'permission_overwrites': [], 'name': 'Game news and event', 'id': '1028336409498615849', 'flags': 0}, {'version': 1665300153588, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 11, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'youtube', 'last_message_id': '1207329449612415026', 'id': '1028568136380846090', 'flags': 0}, {'version': 1665302846910, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 12, 'permission_overwrites': [], 'parent_id': '1028336409498615849', 'name': 'cn', 'last_message_id': '1333564013635834001', 'id': '1028579432987906108', 'flags': 0}, {'version': 1665542368815, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 13, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'name': 'nerdy-questions', 'last_message_id': '1040606428777435137', 'id': '1029584060667932722', 'flags': 0}, {'version': 1665747912555, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 14, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'repair', 'last_message_id': '1355209333251506328', 'id': '1030446173607165962', 'flags': 0}, {'version': 1666014003523, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 15, 'permission_overwrites': [], 'parent_id': '1028336409498615849', 'name': 'goals', 'last_message_id': '1355205985358319748', 'id': '1031562240006037504', 'flags': 0}, {'version': 1743524014718, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 16, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'useful-wbsite', 'last_message_id': '1207317225380380743', 'id': '1035469749242568774', 'flags': 0}, {'version': 1667051327825, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 17, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'projects', 'last_message_id': '1051460356725289060', 'id': '1035913093475217479', 'flags': 0}, {'version': 1667553124408, 'type': 0, 'topic': '<:hydra_play:971015680600199178> Pause/Resume the song.\n<:hydra_stop:971015680696672356> Stop and empty the queue.\n<:hydra_skip:971015680654729216> Skip the song.\n<:hydra_loop_off:971015680629559296> Switch between the loop modes.\n<:hydra_shuffle:971015680633741312> Shuffle the queue.\n<:hydra_button_green:974274003659292682> Add the current song to your private playlist.\n<:hydra_button_red:974274003663482880> Remove the current song from your private playlist.', 'rate_limit_per_user': 0, 'position': 18, 'permission_overwrites': [], 'name': 'hydra-song-requests', 'last_message_id': '1039157009464971354', 'id': '1038017780458475560', 'flags': 0}, {'version': 1674878131820, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 19, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '805307408', 'allow': '0'}], 'parent_id': '979000931146420245', 'name': 'passwords', 'last_message_id': '1068743246223773766', 'id': '1068740321724338318', 'flags': 0}, {'version': 1675778363272, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 20, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'code-share', 'last_message_id': '1072516954176368650', 'id': '1072516933171294218', 'flags': 0}, {'version': 1743524031708, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 21, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '0', 'allow': '0'}], 'parent_id': '1028335612488597544', 'name': 'robot-making', 'last_message_id': '1208283944789737493', 'id': '1207328608717115392', 'flags': 0}, {'version': 1711252141839, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 22, 'permission_overwrites': [{'type': 0, 'id': '979000931146420244', 'deny': '1024', 'allow': '0'}], 'name': 'job', 'last_message_id': '1221304816748462201', 'id': '1221304744505507901', 'flags': 0}, {'version': 1743173041124, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 23, 'permission_overwrites': [], 'name': 'bot', 'last_message_id': '1355212618184265830', 'id': '1355190602039296234', 'flags': 0, 'default_auto_archive_duration': 10080}, {'version': 1743523763295, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 24, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'skill-dev', 'last_message_id': '1358052497448505355', 'id': '1356661735477743727', 'flags': 0}, {'version': 1756721768124, 'type': 0, 'topic': None, 'rate_limit_per_user': 0, 'position': 25, 'permission_overwrites': [], 'parent_id': '979000931146420245', 'name': 'playground', 'last_message_id': '1412069793586217040', 'id': '1412018179873701899', 'flags': 0}]}}
[2025-09-01 19:38:44] [DEBUG   ] discord.client: Dispatching event socket_event_type
[2025-09-01 19:38:44] [DEBUG   ] discord.client: Dispatching event guild_available
[2025-09-01 19:38:46] [DEBUG   ] discord.client: Dispatching event ready
[2025-09-01 19:39:20] [DEBUG   ] discord.gateway: Keeping shard ID None websocket alive with sequence 2.
[2025-09-01 19:39:20] [DEBUG   ] discord.gateway: For Shard ID None: WebSocket Event: {'t': None, 's': None, 'op': 11, 'd': None}
